// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoef;

#nullable disable

namespace proyectoef.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240322014223_InitialDataRetoClase")]
    partial class InitialDataRetoClase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("5d997b60-6592-47ae-a311-44826951c5f3"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("bba57e73-fdc4-4247-93d8-02e49731ea82"),
                            Nombre = "Actividades Personales",
                            Peso = 50
                        },
                        new
                        {
                            CategoriaId = new Guid("bfe30f5b-116a-4781-bb5c-bf956e457201"),
                            Nombre = "Actividades Escolares",
                            Peso = 60
                        },
                        new
                        {
                            CategoriaId = new Guid("19269fe4-2d5c-4d7d-bcae-6ef190b53390"),
                            Nombre = "Actividades Personales",
                            Peso = 20
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<bool>("Terminada")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("3d3c69c7-868c-418b-9bc0-49b4bfd68550"),
                            CategoriaId = new Guid("5d997b60-6592-47ae-a311-44826951c5f3"),
                            FechaCreacion = new DateTime(2024, 3, 21, 19, 42, 22, 359, DateTimeKind.Local).AddTicks(2819),
                            PrioridadTarea = 1,
                            Terminada = false,
                            Titulo = "Pago de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("db64cd9a-f505-4d46-8a2c-68b225aaf50a"),
                            CategoriaId = new Guid("bba57e73-fdc4-4247-93d8-02e49731ea82"),
                            FechaCreacion = new DateTime(2024, 3, 21, 19, 42, 22, 359, DateTimeKind.Local).AddTicks(2837),
                            PrioridadTarea = 0,
                            Terminada = false,
                            Titulo = "Terminar de hacer tu limpieza de Habitacion"
                        },
                        new
                        {
                            TareaId = new Guid("d4250210-9322-4183-b05c-d6199284c09c"),
                            CategoriaId = new Guid("bfe30f5b-116a-4781-bb5c-bf956e457201"),
                            FechaCreacion = new DateTime(2024, 3, 21, 19, 42, 22, 359, DateTimeKind.Local).AddTicks(2842),
                            PrioridadTarea = 2,
                            Terminada = false,
                            Titulo = "Terminar la Web API con el Metodo GET y PUT"
                        },
                        new
                        {
                            TareaId = new Guid("2d18f412-bda7-41de-b19d-99f6837a0811"),
                            CategoriaId = new Guid("19269fe4-2d5c-4d7d-bcae-6ef190b53390"),
                            FechaCreacion = new DateTime(2024, 3, 21, 19, 42, 22, 359, DateTimeKind.Local).AddTicks(2847),
                            PrioridadTarea = 1,
                            Terminada = true,
                            Titulo = "Inscribirse al GYM"
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.HasOne("proyectoef.Models.Categoria", null)
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
